name: Test

on: [push]

jobs:
  test:
    # где заускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v3
      # настраиваем java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        # запускаем тесты
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      # скачиваем историю тестов
      - name: Checkout gh-pages history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      # генерируем отчет
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
      # публикуем отчет
      - name: Publish report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
        with:
          publish_branch: gh-pages
          publish_dir: allure-history